# Generated by Django 5.2.12 on 2026-09-24 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_extensions', '0002_catalog_access_controls'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'catalog categories',
                'ordering': ('display_order', 'name'),
            },
        ),
        migrations.AddField(
            model_name='certificateprogramcatalogmetadata',
            name='catalog_categories',
            field=models.ManyToManyField(blank=True, related_name='certificate_programs', to='catalog_extensions.catalogcategory'),
        ),
        migrations.AddField(
            model_name='certificateprogramcatalogmetadata',
            name='primary_catalog_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='primary_certificate_programs', to='catalog_extensions.catalogcategory'),
        ),
        migrations.AddField(
            model_name='microcoursecatalogmetadata',
            name='catalog_categories',
            field=models.ManyToManyField(blank=True, related_name='microcourses', to='catalog_extensions.catalogcategory'),
        ),
        migrations.AddField(
            model_name='microcoursecatalogmetadata',
            name='primary_catalog_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='primary_microcourses', to='catalog_extensions.catalogcategory'),
        ),
    ]
